name: Yimtaehoon
favicon: null
layout_spectrum: 0.50954
typography_spectrum: 0.527447467437014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.618845799472183
  rhythmicContrast: 0.25
purpose: []
